#!/usr/bin/env python3
path = "src/app/[locale]/components/WorkoutLogsViewer.tsx"

lines = []
lines.append('"use client";')
lines.append('')
lines.append('import { useState, useEffect } from "react";')
lines.append('import { api } from "@/lib/api-client";')
lines.append('')
lines.append('type LogMovementEntry = {')
lines.append('  movement_name: string;')
lines.append('  sets: string;')
lines.append('  reps: string;')
lines.append('  weight: string;')
lines.append('  notes: string;')
lines.append('};')
lines.append('')
lines.append('type LogSectionEntry = {')
lines.append('  section_id: string;')
lines.append('  section_label: string;')
lines.append('  movements: LogMovementEntry[];')
lines.append('};')
lines.append('')
lines.append('type WorkoutLogEntry = {')
lines.append('  user_id: number;')
lines.append('  log_data: LogSectionEntry[];')
lines.append('  updated_at: string;')
lines.append('};')
lines.append('')
lines.append('type AthleteInfo = {')
lines.append('  id: number;')
lines.append('  username: string;')
lines.append('  full_name: string | null;')
lines.append('};')
lines.append('')
lines.append('type Props = {')
lines.append('  open: boolean;')
lines.append('  onClose: () => void;')
lines.append('  workoutDate: string;')
lines.append('};')
lines.append('')
lines.append('function initials(name: string): string {')
lines.append('  return name.trim().slice(0, 2).toUpperCase();')
lines.append('}')
lines.append('')
lines.append('function formatDate(iso: string): string {')
lines.append('  try { return new Date(iso).toLocaleString(); }')
lines.append('  catch { return iso; }')
lines.append('}')
lines.append('')
LINES_SEPARATOR_HERE